"""init tables

Revision ID: 001
Revises: 
Create Date: 2026-04-29 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


def _server_now():
    """返回兼容当前数据库的时间戳默认值表达式"""
    dialect = op.get_bind().dialect.name
    return sa.text('CURRENT_TIMESTAMP') if dialect == 'sqlite' else sa.text('now()')


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_code', sa.String(length=100), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('default_priority', sa.Integer(), nullable=True),
    sa.Column('default_params', sa.JSON(), nullable=False),
    sa.Column('handler_class', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=_server_now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=_server_now(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_metadata_strategy_code'), 'strategy_metadata', ['strategy_code'], unique=True)
    op.create_index(op.f('ix_strategy_metadata_strategy_type'), 'strategy_metadata', ['strategy_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_metadata_strategy_type'), table_name='strategy_metadata')
    op.drop_index(op.f('ix_strategy_metadata_strategy_code'), table_name='strategy_metadata')
    op.drop_table('strategy_metadata')
    # ### end Alembic commands ###
