"""add risk events and reports tables

Revision ID: 6e1c3a6110c1
Revises: df37c9fbe4ad
Create Date: 2026-04-30 16:51:38.413065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


def _server_now():
    """返回兼容当前数据库的时间戳默认值表达式"""
    dialect = op.get_bind().dialect.name
    return sa.text('CURRENT_TIMESTAMP') if dialect == 'sqlite' else sa.text('now()')


# revision identifiers, used by Alembic.
revision: str = '6e1c3a6110c1'
down_revision: Union[str, Sequence[str], None] = 'df37c9fbe4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensitive_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=_server_now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=_server_now(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensitive_words_category'), 'sensitive_words', ['category'], unique=False)
    op.create_index(op.f('ix_sensitive_words_is_enabled'), 'sensitive_words', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_sensitive_words_word'), 'sensitive_words', ['word'], unique=True)
    op.create_table('test_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('scene_name', sa.String(length=100), nullable=False),
    sa.Column('scene_strategy_snapshot', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('passed_requests', sa.Integer(), nullable=True),
    sa.Column('blocked_requests', sa.Integer(), nullable=True),
    sa.Column('block_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('error_code_stats', sa.JSON(), nullable=True),
    sa.Column('strategy_trigger_stats', sa.JSON(), nullable=True),
    sa.Column('key_status_stats', sa.JSON(), nullable=True),
    sa.Column('top_events', sa.JSON(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=_server_now(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_reports_created_at'), 'test_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_reports_is_archived'), 'test_reports', ['is_archived'], unique=False)
    op.create_index(op.f('ix_test_reports_scene_id'), 'test_reports', ['scene_id'], unique=False)
    op.create_index(op.f('ix_test_reports_started_at'), 'test_reports', ['started_at'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('api_key', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_snippet', sa.String(length=1000), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=_server_now(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['test_reports.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_api_key'), 'risk_events', ['api_key'], unique=False)
    op.create_index(op.f('ix_risk_events_created_at'), 'risk_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_events_error_code'), 'risk_events', ['error_code'], unique=False)
    op.create_index(op.f('ix_risk_events_event_type'), 'risk_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_risk_events_ip_address'), 'risk_events', ['ip_address'], unique=False)
    op.create_index(op.f('ix_risk_events_model'), 'risk_events', ['model'], unique=False)
    op.create_index(op.f('ix_risk_events_report_id'), 'risk_events', ['report_id'], unique=False)
    op.create_index(op.f('ix_risk_events_scene_id'), 'risk_events', ['scene_id'], unique=False)
    op.create_index(op.f('ix_risk_events_strategy_id'), 'risk_events', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_events_strategy_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_scene_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_report_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_model'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_ip_address'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_event_type'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_error_code'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_created_at'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_api_key'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_test_reports_started_at'), table_name='test_reports')
    op.drop_index(op.f('ix_test_reports_scene_id'), table_name='test_reports')
    op.drop_index(op.f('ix_test_reports_is_archived'), table_name='test_reports')
    op.drop_index(op.f('ix_test_reports_created_at'), table_name='test_reports')
    op.drop_table('test_reports')
    op.drop_index(op.f('ix_sensitive_words_word'), table_name='sensitive_words')
    op.drop_index(op.f('ix_sensitive_words_is_enabled'), table_name='sensitive_words')
    op.drop_index(op.f('ix_sensitive_words_category'), table_name='sensitive_words')
    op.drop_table('sensitive_words')
    # ### end Alembic commands ###
