"""add scene strategy relation table

Revision ID: df37c9fbe4ad
Revises: f735cc04b9e7
Create Date: 2026-04-30 10:47:25.016105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


def _server_now():
    """返回兼容当前数据库的时间戳默认值表达式"""
    dialect = op.get_bind().dialect.name
    return sa.text('CURRENT_TIMESTAMP') if dialect == 'sqlite' else sa.text('now()')


# revision identifiers, used by Alembic.
revision: str = 'df37c9fbe4ad'
down_revision: Union[str, Sequence[str], None] = 'f735cc04b9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_strategy_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('custom_params', sa.JSON(), nullable=True),
    sa.Column('custom_priority', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=_server_now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=_server_now(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene_strategy_relation')
    # ### end Alembic commands ###
