"""add global config table

Revision ID: f735cc04b9e7
Revises: fa9f216b4f27
Create Date: 2026-04-30 10:36:57.406719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


def _server_now():
    """返回兼容当前数据库的时间戳默认值表达式"""
    dialect = op.get_bind().dialect.name
    return sa.text('CURRENT_TIMESTAMP') if dialect == 'sqlite' else sa.text('now()')


# revision identifiers, used by Alembic.
revision: str = 'f735cc04b9e7'
down_revision: Union[str, Sequence[str], None] = 'fa9f216b4f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_config',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('value_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=_server_now(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_config')
    # ### end Alembic commands ###
