"""add scene pool relation table

Revision ID: fa9f216b4f27
Revises: 301bec9be219
Create Date: 2026-04-29 19:44:13.820061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


def _server_now():
    """返回兼容当前数据库的时间戳默认值表达式"""
    dialect = op.get_bind().dialect.name
    return sa.text('CURRENT_TIMESTAMP') if dialect == 'sqlite' else sa.text('now()')


# revision identifiers, used by Alembic.
revision: str = 'fa9f216b4f27'
down_revision: Union[str, Sequence[str], None] = '301bec9be219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_pool_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=_server_now(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['api_key_pools.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene_pool_relation')
    # ### end Alembic commands ###
